make transion .5 seconds
gladly-team/tab-web pull request #100
Opened 2021-02-04 23:32 UTC by amaliwanag2

2021-02-05 00:11 UTC, amaliwanag2 commented
@kmjennison this is what i did for manual testing:
* couldn't test vercel deployment
* tested locally with javascript disabled and network throttled to slow 3g, looked fine IMO
* tested that the fade works when background image changes after app is already loaded

2021-02-05 18:47 UTC, kmjennison commented
There seems to be some compatibility issue. It looks great in general, but on Firefox when [deployed](https://tab-web-g9gqykivj.vercel.app/newtab/), the image is fairly delayed and doesn't fade in. It works fine on FF when JS is disabled. Chrome works great.

2021-02-05 21:51 UTC, kmjennison commented
To attempt to fix this, I've tried:
* Looking for unexpected prop changes that would be unmounting -- I don't see any
* Using inline styling for the `backgroundImage` property -- doesn't fix the problem
* Using MUI's `Fade` component -- this relies on JS, so it'll be too slow
* Using `react-transition-group`'s `CSSTransition` -- this relies on JS, so it'll be too slow

My suspicion is this is related to how MUI styles are injected during SSR and then loaded in JS. Possibly the switch from CSS to CSS-in-JS is causing some unexpected rendering in Firefox. **We could try using a CSS animation outside of MUI.**

Alternatively, maybe this is just a performance issue with Firefox.

2021-02-05 22:37 UTC, kmjennison commented
I tried a CSS animation using CSS modules, but it had the same issue. Starting to suspect it's just a performance difference between the browsers.

2021-02-05 22:41 UTC, kmjennison requested changes
@amaliwanag2 Would love your thoughts on the fade issue I'm encountering in Firefox. (See my barrage of comments/commits—no luck fixing it.) Maybe we just leave it for now.

2021-02-05 22:41 UTC, kmjennison commented on src/components/UserBackgroundImage.js
> +    animation: '$fadeIn 0.5s ease',
Let's move the animation to the root element so that it fades in the "tint" component, too.

2021-02-08 16:35 UTC, kmjennison commented
I wonder if the performance hit comes during React hydration (e.g., is there a hydration mismatch?). When JS is enabled, I see a full page repaint after mount.

2021-02-09 00:12 UTC, kmjennison approved these changes
UX question for the future: should we fade the whole page (like this PR) or just the image? We should do whatever is perceived smoother/faster.

2021-02-09 03:55 UTC, merged