TFAC-112 Adding LogUserRevenueMutation
gladly-team/tab-web pull request #122
Opened 2021-02-27 20:48 UTC by jedtan

2021-03-01 23:40 UTC, kmjennison requested changes

2021-03-01 23:40 UTC, kmjennison commented on src/__tests__/pages/index.test.js
> +    console.log(wrapper.debug())
Remove console log

2021-03-01 23:40 UTC, kmjennison commented on src/__tests__/pages/index.test.js
> +    console.log(wrapper.debug())
Remove

2021-03-01 23:40 UTC, kmjennison commented on src/__tests__/pages/index.test.js
> +    console.log(wrapper.debug())
Remove

2021-03-01 23:40 UTC, kmjennison commented on src/pages/index.js
>      console.log('Ad displayed:', displayedAdInfo, context) // eslint-disable-line no-console
Go ahead and remove this console log, too.

2021-03-01 23:40 UTC, kmjennison commented on src/utils/mutations/__tests__/LogUserRevenueMutation.test.js
> +/* eslint-env jest */
You can remove this eslint line. Our config in this repo will assume `*.test.js` files are a Jest env.

2021-03-02 01:09 UTC, jedtan commented on src/__tests__/pages/index.test.js
> +    console.log(wrapper.debug())
Whoops!

2021-03-02 01:25 UTC, merged