TFAC-212 Add Click Overlay to MoneyRaised Counter
gladly-team/tab-web pull request #126
Opened 2021-03-11 01:33 UTC by jedtan

2021-03-11 03:45 UTC, kmjennison requested changes

2021-03-11 03:45 UTC, kmjennison commented on src/components/DashboardPopover.js
> +        style={{
Move to class with `makeStyles`.

2021-03-11 03:45 UTC, kmjennison commented on src/components/MoneyRaised.js
> +            padding: 12,
Use class styling.

2021-03-11 03:45 UTC, kmjennison commented on src/components/__tests__/DashboardPopover.test.js
> +      shallow(<DashboardPopover {...mockProps} />).dive()
Remove unneeded `.dive()` from tests.

2021-03-11 08:07 UTC, jedtan commented on src/components/__tests__/MoneyRaised.test.js
> +  it('popover onClose sets isPopoverOpen to false', () => {
This one is really stumping me as it's failing. Would you mind taking a look @kmjennison, hope I'm not missing something obvious.

2021-03-12 17:40 UTC, kmjennison requested changes
Looks good! Just want to make some tiny style tweaks.

2021-03-12 17:40 UTC, kmjennison commented on src/components/MoneyRaised.js
> +  popover: { marginTop: 12 },
Please reduce to 9px (aligns with impact notification layout).

2021-03-12 17:40 UTC, kmjennison commented on src/components/MoneyRaised.js
> +      <Button ref={spanRef} onClick={() => setIsPopoverOpen(true)}>
The button adds some additional margin that increased the menu spacing. Let's compensate for it so the menu stays approx the same: I think you can remove the `moneyRaisedContainer` class margin in index.js.

2021-03-15 16:29 UTC, merged