recache page after mutation
gladly-team/tab-web pull request #127
Opened 2021-03-12 19:17 UTC by amaliwanag2

@kmjennison I *think* we still want a stale while revalidating strategy to cache assets besidies the /newtab page but I left a comment in the workbox config with more details

2021-03-12 19:52 UTC, kmjennison requested changes
Nice work!

2021-03-12 19:52 UTC, kmjennison commented on .eslintrc.js
> +    'no-unused-expressions': ['error', { allowShortCircuit: true }],
Let's not disable this. I agree with [this criticism](https://github.com/airbnb/javascript/issues/963#issuecomment-235048756) of readability.

2021-03-12 19:52 UTC, kmjennison commented on src/utils/mutations/callMutation.js
> +  cache && recachePage()
Use `if(cache) { ... }`

2021-03-12 19:52 UTC, kmjennison commented on next.config.js
> +        // This is less common in workbox, but can be useful if you have your own precaching step.""
Yes, let's just leave this for now. If we did cache only, we'd want it only for the `newtab` resource, and that's just an optimization that could cause a bug of serving stale resources (for example, if we modify/disable the recaching mutation logic).

Go ahead and remove comments.

2021-03-15 18:29 UTC, amaliwanag2 commented on next.config.js
> +        // see caching strategies here https://developers.google.com/web/tools/workbox/modules/workbox-strategies
still seems useful to have this one line

2021-03-17 01:22 UTC, kmjennison approved these changes
LGTM 🍝

2021-03-17 01:22 UTC, merged