TFAC-1117 Presentational Components for new SFAC Tab Page Component
gladly-team/tab-web pull request #372
Opened 2022-08-31 19:40 UTC by jedtan

2022-09-07 19:02 UTC, kmjennison requested changes
Good progress on this! Requested some changes in UI and props. Also see Chromatic comments for UI feedback.

2022-09-07 19:02 UTC, kmjennison commented on src/components/SfacActivityNotification.stories.jsx
> +}
Please also provide a set with a different cause name, e.g. "Reproductive Health"

2022-09-08 03:08 UTC, jedtan commented on src/components/SfacActivityNotification.js
> +  const [open, setOpen] = useState(true)
I actually have this refactor in the next PR. Going to be lazy and keep it in that separate branch.

2022-09-09 21:34 UTC, kmjennison submitted a review, later dismissed
UI is looking great! Please just keep using the Button components within the links, then this should be good to ship. Thanks!

2022-09-09 21:34 UTC, kmjennison commented on src/components/SfacActivityNotification.js
> +          FEEDBACK
Thanks for changing to links! However, these should also still use the Button component (consistent UI when interacting, likely better accessibility).

2022-09-09 21:34 UTC, kmjennison commented on src/components/SfacActivityNotification.stories.jsx
> +  return <SfacActivityNotification {...args} className={classes.widthDiv} />
Perfect, thanks for this edit!

2022-09-10 21:21 UTC, merged